# Dockerfile.api-gateway
FROM base as development

WORKDIR /app
RUN npm run build dashboard-and-network

FROM base as production

WORKDIR /app
COPY --from=development /app/dist ./dist
CMD ["node", "dist/apps/dashboard-and-network/main"]
