version: '3'
services:
  nginx:
    ports:
      - '80:80'
  api-gateway:
    build:
      target: production
      args:
        - NODE_ENV=production
  auth:
    build:
      target: production
      args:
        - NODE_ENV=production
