version: '3'
services:
  api-gateway:
    build:
      context: .
      target: development
      args:
        - NODE_ENV=development
    volumes:
      - .:/learningPlatform/code/api-gateway
      - /learningPlatform/code/api-gateway/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:dev api-gateway
  auth:
    build:
      context: .
      target: development
      args:
        - NODE_ENV=development
    volumes:
      - .:/learningPlatform/code/auth
      - /learningPlatform/code/auth/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:dev auth
