version: '3'
services:
  nginx:
    ports:
      - '80:80'
  auth:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: node ./dist/main.js
