version: '3'
services:
  # api-gateway:
  #   build:
  #     context: .
  #     target: development
  #     args:
  #       - NODE_ENV=development
  #   volumes:
  #     - .:/learningPlatform/code/api-gateway
  #     - /learningPlatform/code/api-gateway/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run start:dev api-gateway
  video-processing:
    build:
      context: .
      target: development
      args:
        - NODE_ENV=development
    volumes:
      - .:/learningPlatform/code/video-processing
      - /learningPlatform/code/video-processing/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:dev video-processing
  # dashboard-and-network:
  #   build:
  #     context: .
  #     target: development
  #     args:
  #       - NODE_ENV=development
  #   volumes:
  #     - .:/learningPlatform/code/dashboard-and-network
  #     - /learningPlatform/code/dashboard-and-network/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run start:dev dashboard-and-network
  # auth:
  #   build:
  #     context: .
  #     target: development
  #     args:
  #       - NODE_ENV=development
  #   volumes:
  #     - .:/learningPlatform/code/auth
  #     - /learningPlatform/code/auth/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run start:dev auth
  # streaming:
  #   build:
  #     context: .
  #     target: development
  #     args:
  #       - NODE_ENV=development
  #   volumes:
  #     - .:/learningPlatform/code/streaming
  #     - /learningPlatform/code/streaming/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run start:dev streaming
